name: Test on Multiple Operating Systems

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18, 20, 22]
        attempt: [1, 2, 3, 4, 5]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clean and install dependencies
        run: |
          echo "Cleaning dependencies..."
          rm -rf node_modules package-lock.json || true
          echo "Installing dependencies..."
          npm ci
        shell: bash

      - name: Run tests (OS: ${{ matrix.os }}, Node.js: ${{ matrix.node-version }}, Attempt: ${{ matrix.attempt }})
        run: |
          echo "Starting test attempt #${{ matrix.attempt }}..."
          npm test
